version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8080"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
