version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "${BACKEND_PORT}:8080"
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERT_PATH}:/etc/nginx/certs/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - backend
  
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - /etc/letsencrypt/live/45-126-126-118.cloud-xip.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
  #     - /etc/letsencrypt/live/45-126-126-118.cloud-xip.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
  #   depends_on:
  #     - frontend
  #     - backend
