services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8080"
    environment:
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - KEYCLOAK_JWK_SET_URI=${KEYCLOAK_JWK_SET_URI}
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERT_PATH}:/etc/nginx/certs/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/nginx/certs/privkey.pem:ro
    environment:
      - VITE_KEYCLOAK_URL=${KEYCLOAK_URL}
      - VITE_KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - VITE_KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
    depends_on:
      - backend
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT_PATH}
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/vitira-realm.json:${KEYCLOAK_IMPORT_PATH}:ro

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - /etc/letsencrypt/live/45-126-126-118.cloud-xip.com/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
  #     - /etc/letsencrypt/live/45-126-126-118.cloud-xip.com/privkey.pem:/etc/nginx/certs/privkey.pem:ro
  #   depends_on:
  #     - frontend
  #     - backend
