name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts
      
      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} <<EOF
          mkdir -p apps
          ls -la
          EOF

      - name: Copy files to VM
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/${{ secrets.VM_USERNAME }}/apps

      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
            cd /${{ secrets.VM_USERNAME }}/apps
            docker-compose down || true
            docker-compose up --build -d
          EOF 